### ISSUE TITLE
2.3.Desarrollo de productos (Keto)

### ISSUE THREAD

**Issue by Gise07** [CodeSystem2022/TEAM-FORTRAN-Proyecto-Integrador-Cuarto-Semestre#5]

**Comment by HidoGG** [comment]
Trabajando en las tareas  :
Nombre los productos Keto.
Agregue imágenes nuevas de productos keto, porque habían repetidas.
Las imágenes, no estaban bien redireccionadas. "/img/...", tenian que estar "img/..." .
